import { Widget } from "@/components/widget/widget";
import { resolveWidgetLang, resolveWidgetTheme } from "@/lib/widget-params";
import demo from "@/lib/demo/demo-data.json";

// Static fixture, no Convex call: the demo cannot be abused and works offline.
export default async function DemoWidgetPage({
  searchParams,
}: {
  searchParams: Promise<{ [key: string]: string | string[] | undefined }>;
}) {
  const sp = await searchParams;
  return (
    <Widget
      demo
      preview={false}
      // The fixture is generated by the real catalogue pipeline; its shape matches the public query.
      configurator={demo.configurator as never}
      theme={resolveWidgetTheme(sp.theme, "auto")}
      lang={resolveWidgetLang(sp.lang, "it")}
    />
  );
}
